### ISSUE TITLE
Dataset selection

### ISSUE THREAD

**Issue by jmarkgraf** [mberneaud/DataScienceAssignment1#1]
Which datasets are we using?

**Comment by mberneaud** [comment]
Hey Jonas, I decided to use the "Orange" dataset, which contains data on the age and trunk circumference of 5 orange trees

**Comment by jmarkgraf** [comment]
Hey Malte, other things kept me busy longer than expected, but now I'm starting, too. I gonna work with the "LifeCycleSavings" dataset, a cross-country dataset including information on personal savings, per-capita income, growth rate of per-capita income as well as the age structure of the respective country.

**Comment by mberneaud** [comment]
Alright. Thanks for letting me know on here. I'll mark this issue as closed and we'll see each other tomorrow!
