### ISSUE TITLE
Measures of central tendency and dispersion

### ISSUE THREAD

**Issue by jmarkgraf** [mberneaud/DataScienceAssignment1#2]
We should agree on a set of analytical steps that we conduct for both datasets. Of course, some additional steps can be taken for each dataset as they might have their idiosyncrasies, but for harmonisation we could quickly talk tomorrow about a coherent style of commenting and the analytical steps for each dataset.

**Comment by mberneaud** [comment]
I guess that since we are approaching the deadline and this really isn't super important for the grade, we can skip on this harmonisation and just leave our repo as it is after merging in Diego's pull request.
