### ISSUE TITLE
Additional graphs and presentation of results

### ISSUE THREAD

**Issue by jmarkgraf** [mberneaud/DataScienceAssignment1#3]
We further should discuss how we could present our analytical results in the best way. So far, I only have the .R file. I saw you already have some graphs exported. I could do that too. Let's have a brief talk on how to present our findings / results tomorrow.

**Comment by mberneaud** [comment]
Are you aware whether we need to present our findings in two weeks time or whether this is not necessary after all? I always get confused about this. In this case it would be a good idea to harmonize our results, as you suggested in class.

**Comment by jmarkgraf** [comment]
You mean if each group has to present its findings in class? I doubt that as it would steal us an entire session. The only advice Chris gave me yesterday was not to spend too much time on the assignment as it's supposed to be a very basic intro to R and Git.

**Comment by mberneaud** [comment]
Okay, then leave our stuff as it is now and just do that pull request with Isabel and Diego and be done with it afterwards. 

Their repo for the assignment can be found [here](https://github.com/imiller88/DiegoandIsabellesFantasticalFirstRepository).

**Comment by jmarkgraf** [comment]
I just wanted to have a look at Isabel's and Diego's files in order to do a pull request before Monday as agreed, but it seems their R files are all empty. Do you have access to their actual files (maybe they didn't synchronize their changes...) or am I doing anything wrong?

**Comment by mberneaud** [comment]
Hey Jonas, sorry for the delay in responding, I read your email but forgot to reply on here. For me, my forked repo remained in the state it was in when I initially forked it from Diego and Isabel, so I had to delete it first and then create a new fork to get the changes they made into my fork. If there is a more elegant way to do this, please tell me. I'm sure it must be possible to just pull down their changes into your fork or fetch/merge separately. I'll make some changes now, make a pull request and see where we can discuss it with them (whether there is a discussion thing on the pull request itself or whether I have to open an issue on their repo).

**Comment by mberneaud** [comment]
Did that pull request now and waiting for Isabelle to respond. It turns out that the pull requests have a pretty comfy interface where your commit message gets set as the original message for the pull request, but it allows you to make changes to it. Moreover, a little discussion like this issue is opened to discuss the request.
