### ISSUE TITLE
commentary

### ISSUE THREAD

**Issue by sloloris** [mberneaud/DataScienceAssignment1#4]
It looks really good, guys, we've barely got any commentary. But: 

-perhaps describe more clearly and earlier on what the dataset Orange actually describes - you explain all the variables very briefly, but substantively we don't actually know what the variables show. I had to ?Orange to understand that it was called orange because they are orange trees. It also only becomes clear after poking around a bit that you're talking about trees.
-the same applies for the presentation documents, although we don't even actually need to do those, so it doesn't matter.
-We would also suggest considering making a single README file for the whole repository that describes each of the folders and their contents, rather than forcing the user to have to poke around all the different ones. 

Otherwise looks good guys.

**Comment by mberneaud** [comment]
Well to complete the assignment, we need to incorporate a pull request into our repository as well. So could you fork our repository, introduce some of the changes you proposed in your fork and then issue a pull request to our repo?

Then we could get that last step done towards finishing the assignment.

**Comment by sloloris** [comment]
Sorry, I thought I did that. I just edited your readme a bit. Diego is
going to make some changes too.

**Comment by mberneaud** [comment]
I don't see any pull requests on this repo currently. Did you issue the pull request yet?

**Comment by sloloris** [comment]
hmm, I thought we did. we created a fork and made some changes, at the very
least.

**Comment by mberneaud** [comment]
Well, we have it now and everything works. Diego and I already talked about it at the end of class today.
